// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcns9nNQSeJt7GkMySHbIigskhnG-bP4',
    appId: '1:905337002879:web:575cd3eb0ce494f1ced84a',
    messagingSenderId: '905337002879',
    projectId: 'hireme-5bf75',
    authDomain: 'hireme-5bf75.firebaseapp.com',
    storageBucket: 'hireme-5bf75.firebasestorage.app',
    measurementId: 'G-L4WWX8XDV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREYtsJSw0hOynVSekrdpjxvFXMlicw6Q',
    appId: '1:905337002879:android:590a44320cac36e2ced84a',
    messagingSenderId: '905337002879',
    projectId: 'hireme-5bf75',
    storageBucket: 'hireme-5bf75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgcP8S7jv1anrvStIaCpKsfvWyZXBTj4M',
    appId: '1:905337002879:ios:eafe415f41a61e3cced84a',
    messagingSenderId: '905337002879',
    projectId: 'hireme-5bf75',
    storageBucket: 'hireme-5bf75.firebasestorage.app',
    iosBundleId: 'com.example.hiremeFinalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgcP8S7jv1anrvStIaCpKsfvWyZXBTj4M',
    appId: '1:905337002879:ios:eafe415f41a61e3cced84a',
    messagingSenderId: '905337002879',
    projectId: 'hireme-5bf75',
    storageBucket: 'hireme-5bf75.firebasestorage.app',
    iosBundleId: 'com.example.hiremeFinalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcns9nNQSeJt7GkMySHbIigskhnG-bP4',
    appId: '1:905337002879:web:3c9b79c6ca761b1dced84a',
    messagingSenderId: '905337002879',
    projectId: 'hireme-5bf75',
    authDomain: 'hireme-5bf75.firebaseapp.com',
    storageBucket: 'hireme-5bf75.firebasestorage.app',
    measurementId: 'G-MLKW1BM1DH',
  );
}
